// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protoevents/merchant_service.proto

package protoevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantGoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantGoodsRequest) Reset() {
	*x = MerchantGoodsRequest{}
	mi := &file_protoevents_merchant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantGoodsRequest) ProtoMessage() {}

func (x *MerchantGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoevents_merchant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantGoodsRequest.ProtoReflect.Descriptor instead.
func (*MerchantGoodsRequest) Descriptor() ([]byte, []int) {
	return file_protoevents_merchant_service_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantGoodsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type Goods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_protoevents_merchant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_protoevents_merchant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_protoevents_merchant_service_proto_rawDescGZIP(), []int{1}
}

func (x *Goods) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Goods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goods) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Goods) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Goods) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Goods) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type MerchantGoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         []*Goods               `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantGoodsResponse) Reset() {
	*x = MerchantGoodsResponse{}
	mi := &file_protoevents_merchant_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantGoodsResponse) ProtoMessage() {}

func (x *MerchantGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoevents_merchant_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantGoodsResponse.ProtoReflect.Descriptor instead.
func (*MerchantGoodsResponse) Descriptor() ([]byte, []int) {
	return file_protoevents_merchant_service_proto_rawDescGZIP(), []int{2}
}

func (x *MerchantGoodsResponse) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

var File_protoevents_merchant_service_proto protoreflect.FileDescriptor

const file_protoevents_merchant_service_proto_rawDesc = "" +
	"\n" +
	"\"protoevents/merchant_service.proto\x12\vprotoevents\"7\n" +
	"\x14MerchantGoodsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\x9d\x01\n" +
	"\x05Goods\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\"A\n" +
	"\x15MerchantGoodsResponse\x12(\n" +
	"\x05goods\x18\x01 \x03(\v2\x12.protoevents.GoodsR\x05goodsB?Z=github.com/L30Y3/nandemo/shared/proto/protoevents;protoeventsb\x06proto3"

var (
	file_protoevents_merchant_service_proto_rawDescOnce sync.Once
	file_protoevents_merchant_service_proto_rawDescData []byte
)

func file_protoevents_merchant_service_proto_rawDescGZIP() []byte {
	file_protoevents_merchant_service_proto_rawDescOnce.Do(func() {
		file_protoevents_merchant_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoevents_merchant_service_proto_rawDesc), len(file_protoevents_merchant_service_proto_rawDesc)))
	})
	return file_protoevents_merchant_service_proto_rawDescData
}

var file_protoevents_merchant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protoevents_merchant_service_proto_goTypes = []any{
	(*MerchantGoodsRequest)(nil),  // 0: protoevents.MerchantGoodsRequest
	(*Goods)(nil),                 // 1: protoevents.Goods
	(*MerchantGoodsResponse)(nil), // 2: protoevents.MerchantGoodsResponse
}
var file_protoevents_merchant_service_proto_depIdxs = []int32{
	1, // 0: protoevents.MerchantGoodsResponse.goods:type_name -> protoevents.Goods
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoevents_merchant_service_proto_init() }
func file_protoevents_merchant_service_proto_init() {
	if File_protoevents_merchant_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoevents_merchant_service_proto_rawDesc), len(file_protoevents_merchant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoevents_merchant_service_proto_goTypes,
		DependencyIndexes: file_protoevents_merchant_service_proto_depIdxs,
		MessageInfos:      file_protoevents_merchant_service_proto_msgTypes,
	}.Build()
	File_protoevents_merchant_service_proto = out.File
	file_protoevents_merchant_service_proto_goTypes = nil
	file_protoevents_merchant_service_proto_depIdxs = nil
}
