// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protoevents/order_created.proto

package protoevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Items         []string               `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_protoevents_order_created_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_protoevents_order_created_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_protoevents_order_created_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedEvent) Reset() {
	*x = OrderCreatedEvent{}
	mi := &file_protoevents_order_created_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedEvent) ProtoMessage() {}

func (x *OrderCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protoevents_order_created_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedEvent.ProtoReflect.Descriptor instead.
func (*OrderCreatedEvent) Descriptor() ([]byte, []int) {
	return file_protoevents_order_created_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderCreatedEvent) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_protoevents_order_created_proto protoreflect.FileDescriptor

const file_protoevents_order_created_proto_rawDesc = "" +
	"\n" +
	"\x1fprotoevents/order_created.proto\x12\vprotoevents\"\x7f\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05items\x18\x04 \x03(\tR\x05items\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"X\n" +
	"\x11OrderCreatedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12(\n" +
	"\x05order\x18\x02 \x01(\v2\x12.protoevents.OrderR\x05orderB?Z=github.com/L30Y3/nandemo/shared/proto/protoevents;protoeventsb\x06proto3"

var (
	file_protoevents_order_created_proto_rawDescOnce sync.Once
	file_protoevents_order_created_proto_rawDescData []byte
)

func file_protoevents_order_created_proto_rawDescGZIP() []byte {
	file_protoevents_order_created_proto_rawDescOnce.Do(func() {
		file_protoevents_order_created_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoevents_order_created_proto_rawDesc), len(file_protoevents_order_created_proto_rawDesc)))
	})
	return file_protoevents_order_created_proto_rawDescData
}

var file_protoevents_order_created_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoevents_order_created_proto_goTypes = []any{
	(*Order)(nil),             // 0: protoevents.Order
	(*OrderCreatedEvent)(nil), // 1: protoevents.OrderCreatedEvent
}
var file_protoevents_order_created_proto_depIdxs = []int32{
	0, // 0: protoevents.OrderCreatedEvent.order:type_name -> protoevents.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoevents_order_created_proto_init() }
func file_protoevents_order_created_proto_init() {
	if File_protoevents_order_created_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoevents_order_created_proto_rawDesc), len(file_protoevents_order_created_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoevents_order_created_proto_goTypes,
		DependencyIndexes: file_protoevents_order_created_proto_depIdxs,
		MessageInfos:      file_protoevents_order_created_proto_msgTypes,
	}.Build()
	File_protoevents_order_created_proto = out.File
	file_protoevents_order_created_proto_goTypes = nil
	file_protoevents_order_created_proto_depIdxs = nil
}
