services:
  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ORDER_SERVICE_HOST=http://order-service
      - MERCHANT_SERVICE_HOST=http://merchant-service
      - FIRESTORE_EMULATOR_HOST=firestore:8081
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - IN_CONTAINER=true
    depends_on:
      - merchant-service
      - order-service
      - firestore
      - pubsub

  merchant-service:
    build:
      context: .
      dockerfile: merchant-service/Dockerfile
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8081
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - IN_CONTAINER=true
      - CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/dev/null
      - CLOUDSDK_CORE_PROJECT=nandemo-464411
      - CLOUDSDK_CORE_ACCOUNT=fake-user@example.com
      - DISABLE_PUBSUB=false

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
      - IN_CONTAINER=true

  firestore:
    image: google/cloud-sdk:latest
    platform: linux/amd64
    entrypoint: ["gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:8081"]
    ports:
      - "8081:8081"

  pubsub:
    image: google/cloud-sdk:latest
    platform: linux/amd64
    entrypoint: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8681"]
    ports:
      - "8681:8681"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8681"]
      interval: 2s
      timeout: 2s
      retries: 10

  pubsub-init:
    image: google/cloud-sdk:latest
    platform: linux/amd64
    depends_on:
      pubsub:
        condition: service_healthy
    entrypoint: >
      bash -c "
        set -x &&
        until curl -s http://pubsub:8681 > /dev/null; do echo waiting for pubsub...; sleep 1; done &&
        curl -X PUT -H 'Content-Type: application/json' -d '{\"name\":\"projects/nandemo-464411/topics/order-created\"}' http://pubsub:8681/v1/projects/nandemo-464411/topics/order-created
        curl -X PUT -H \"Content-Type: application/json\" -d '{\"topic\":\"projects/nandemo-464411/topics/order-created\"}' http://pubsub:8681/v1/projects/nandemo-464411/subscriptions/merchant-order-receiver
      "

networks:
  default:
    name: nandemo-network
